spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  mail :
    host : smtp.gmail.com
    port : 587
    username : ${MAIL_USERNAME:}
    password : ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth : true
          starttls:
            enable : true
#          connectiontimeout : 100
#          timeout : 100
#          writetimeout : 100
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 300
  refreshable-duration: 3600

server:
  port: 8080
  servlet:
    context-path: /auction