spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  mail :
    host : smtp.gmail.com
    port : 587
    username : ${MAIL_USERNAME:}
    password : ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth : true
          starttls:
            enable : true
#          connectiontimeout : 100
#          timeout : 100
#          writetimeout : 100
  data:
    redis:
      host: localhost
      port: 6379
      ssl:
        enabled: true

jwt:
  signerKey: ${JWT_SIGNER_KEY:}
  valid-duration: ${JWT_VALID_DURATION:}
  refreshable-duration: ${JWT_REFRESH:}

server:
  port: 8080
  servlet:
    context-path: /auction
    
websocket:
  endpoint: /ws